#!/usr/bin/env php
<?php

/**
 * This file is part of CodeIgniter 4 framework.
 *
 * (c) CodeIgniter Foundation <admin@codeigniter.com>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

$license = __DIR__ . '/../../LICENSE';

$oldLicense = @file_get_contents($license);

if ((string) $oldLicense === '') {
    echo 'Failed to get the contents of LICENSE. It is either not found or not readable.';

    exit(1);
}

$updatedLicense = preg_replace('/\b2019\-\d{4}\b/', '2019-' . date('Y'), $oldLicense);

if ($updatedLicense === $oldLicense) {
    echo 'Nothing to update. LICENSE file is good.';

    exit(0);
}

if (file_put_contents($license, $updatedLicense) === false) {
    echo 'Failed updating license year inside LICENSE. Please do it manually.';

    exit(1);
}
