language: php

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

# Recommended by Travis support
sudo: required
dist: trusty
group: edge

script:
  - php vendor/bin/phpunit -v

before_script:
  - composer install --prefer-source

